services:
  ontime:
    container_name: ontime
    image: getontime/ontime:latest
    ports:
      - "4001:4001/tcp"
      - "8888:8888/udp"
      - "9999:9999/udp"
    volumes:
      - "./ontime-data:/data/"
      - "/usr/local/share/fonts:/usr/local/share/fonts"
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
